variables:
  PROD_BACKEND_URL: "recru-app-backend.scalac.io"
  DEVEL_BACKEND_URL: "recru-app-devel-backend.scalac.io"
  PROD_S3_BUCKET: "new.scalac.io"
  DEVEL_S3_BUCKET: "devel-new.scalac.io"
  PROD_CLOUDFRONT_ID: "E39OM94WC3J4I3"
  DEVEL_CLOUDFRONT_ID: "E3CQDMNIMIRHIN"
cache:
  paths:
  - build/

stages:
  - build
  - deploy

build:
  stage: build
  image: node:4.8.7
  script:
    - npm install
    - node_modules/.bin/gulp build -p
    - mv build/app-*.css build/app.css
    - mv build/app-*.js build/app.js
    - sed -i 's#../../../assets#./assets#g' build/app.js
    - chmod -R 777 build

deploy_devel:
  stage: deploy
  variables:
    S3_BUCKET: $DEVEL_S3_BUCKET
    CLOUDFRONT_ID: $DEVEL_CLOUDFRONT_ID
    BACKEND_URL: $DEVEL_BACKEND_URL
  image:
    name: fstab/aws-cli:latest
    entrypoint: [""]
  script:
    - set -x 
    - sed -i "s#${PROD_BACKEND_URL}#${BACKEND_URL}#g" build/app.js
    - export EPOCH=$(date +%s)
    # retain last 5 backups
    - /home/aws/aws/env/bin/aws s3 ls s3://${S3_BUCKET}/ | egrep -o "join_us_[[:digit:]]+" | egrep -o '[[:digit:]]+$' | sort -r |  tail -n +5 | xargs -n 1 -I {} /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us_{} --recursive
    - /home/aws/aws/env/bin/aws s3 cp s3://${S3_BUCKET}/join_us s3://${S3_BUCKET}/join_us_${EPOCH} --recursive
    - /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us/ --recursive
    - /home/aws/aws/env/bin/aws s3 cp assets s3://${S3_BUCKET}/join_us/assets --recursive
    - /home/aws/aws/env/bin/aws s3 cp build/ s3://${S3_BUCKET}/join_us/ --recursive
    - /home/aws/aws/env/bin/aws s3 cp index.html s3://${S3_BUCKET}/join_us/
    - /home/aws/aws/env/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    - devel
  environment:
    name: $CI_COMMIT_REF_NAME

revert_devel:
  stage: deploy
  variables:
    S3_BUCKET: $DEVEL_S3_BUCKET
    CLOUDFRONT_ID: $DEVEL_CLOUDFRONT_ID
    BACKEND_URL: $DEVEL_BACKEND_URL
  image:
    name: fstab/aws-cli:latest
    entrypoint: [""]
  script:
    - set -x 
    - /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us/ --recursive
    - NEWEST_EPOCH=$(/home/aws/aws/env/bin/aws s3 ls s3://${S3_BUCKET}/ | egrep -o "join_us_[[:digit:]]+" | egrep -o '[[:digit:]]+$' | sort -r | head -1)
    - /home/aws/aws/env/bin/aws s3 cp s3://${S3_BUCKET}/join_us_${NEWEST_EPOCH} s3://${S3_BUCKET}/join_us --recursive
    - /home/aws/aws/env/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    - devel
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME


deploy_production:
  stage: deploy
  variables:
    S3_BUCKET: $PROD_S3_BUCKET
    CLOUDFRONT_ID: $PROD_CLOUDFRONT_ID
    BACKEND_URL: $PROD_BACKEND_URL
  image:
    name: fstab/aws-cli:latest
    entrypoint: [""]
  script:
    - set -x 
    - export EPOCH=$(date +%s)
    # retain last 5 backups
    - /home/aws/aws/env/bin/aws s3 ls s3://${S3_BUCKET}/ | egrep -o "join_us_[[:digit:]]+" | egrep -o '[[:digit:]]+$' | sort -r |  tail -n +5 | xargs -n 1 -I {} /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us_{} --recursive
    - /home/aws/aws/env/bin/aws s3 cp s3://${S3_BUCKET}/join_us s3://${S3_BUCKET}/join_us_${EPOCH} --recursive
    - /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us/ --recursive
    - /home/aws/aws/env/bin/aws s3 cp assets s3://${S3_BUCKET}/join_us/assets --recursive
    - /home/aws/aws/env/bin/aws s3 cp build/ s3://${S3_BUCKET}/join_us/ --recursive
    - /home/aws/aws/env/bin/aws s3 cp index.html s3://${S3_BUCKET}/join_us/
    - /home/aws/aws/env/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    - master
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME

revert_production:
  stage: deploy
  variables:
    S3_BUCKET: $PROD_S3_BUCKET
    CLOUDFRONT_ID: $PROD_CLOUDFRONT_ID
    BACKEND_URL: $PROD_BACKEND_URL
  image:
    name: fstab/aws-cli:latest
    entrypoint: [""]
  script:
    - set -x 
    - /home/aws/aws/env/bin/aws s3 rm s3://${S3_BUCKET}/join_us/ --recursive
    - NEWEST_EPOCH=$(/home/aws/aws/env/bin/aws s3 ls s3://${S3_BUCKET}/ | egrep -o "join_us_[[:digit:]]+" | egrep -o '[[:digit:]]+$' | sort -r | head -1)
    - /home/aws/aws/env/bin/aws s3 cp s3://${S3_BUCKET}/join_us_${NEWEST_EPOCH} s3://${S3_BUCKET}/join_us --recursive
    - /home/aws/aws/env/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    - master
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME
