version: '2'
services:
  frontend:
    image: node:4
    expose:
      - 8000
      - 8080
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/src
      - ./tmp/.npm:/root/.npm
    environment:
      - "PATH=$PATH:/src/node_modules/.bin"
      - "DOCKERIZED_DEPLOYMENT=1"
    command: bash -xe -c "cd /src && (([ -d node_modules ] && npm prune gulp && npm prune) || (npm install gulp && npm install)) && gulp"
